[workspace]
  members = [
    "clients",
    "config",
    "domain",
    "store",
    "ui/cli",
    "ui/tui",
    "workflows",
  ]
  resolver = "2"

  [workspace.lints.clippy]
    expect_used = "warn"
    indexing_slicing = "warn"
    nursery = { level = "warn", priority = -1 }
    panic = "warn"
    pedantic = { level = "warn", priority = -1 }
    redundant_pub_crate = "allow"
    unwrap_used = "warn"

  [workspace.lints.rust]
    missing_debug_implementations = "deny"
    missing_docs = "warn"
    unreachable_pub = "warn"
    unsafe_code = "forbid"
    unused_results = "deny"

  [workspace.lints.rustdoc]
    broken_intra_doc_links = "deny"
