[package]
  edition = "2021"
  name = "config"
  version = "0.1.0"

[dependencies]
  anyhow = "1"
  domain = { path = "../domain" }
  secrecy = "0.8"
  serde = { version = "1", features = ["derive"] }
  tokio = { version = "1", features = ["full"] }
  toml = "0.8"

[dev-dependencies]
  insta = "1"
  proptest = "1"
  rstest = "0.25"
